[jupiter.cron.test]
    withSeconds = false
    concurrentDelay= "10s"
    immediatelyRun = false
    # 分布式任务的开关
    distributedTask = true
    endpoints = ["127.0.0.1:2379"]
    connectTimeout = "10s"
